export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const SET_USERNAME = 'SET_USERNAME';
export const LOAD_GAMES_SCHEDULES_SUCCESS = 'LOAD_GAMES_SCHEDULES_SUCCESS';
export const CREATE_SCHEDULE_SUCCESS = 'CREATE_SCHEDULE_SUCCESS';
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS';
export const REMOVE_SCHEDULE_SUCCESS = 'REMOVE_SCHEDULE_SUCCESS';
